# -*- coding: utf-8 -*-
"""tasks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GlaDm01a0tijrLvctL0C8YDVbrdC5U7J

1. Parking Lot Management: Track vehicle entry/exit, available spots, and compute parking fees
"""

class Parking:

    def __init__(self):
        self.spots = 5
        self.data = {}

    def entry(self):
        v = input("Vehicle no: ")
        t = int(input("Entry hour: "))
        if self.spots > 0:
            self.data[v] = t
            self.spots -= 1
            print("Parked")
        else:
            print("No space")

    def exit(self):
        v = input("Vehicle no: ")
        if v in self.data:
            out = int(input("Exit hour: "))
            hours = out - self.data[v]
            fee = hours * 10
            print("Fee =", fee)
            del self.data[v]
            self.spots += 1
        else:
            print("Not found")

    def available(self):
        print("Available spots:", self.spots)


p = Parking()

while True:
    print("\n1.Entry")
    print("2.Exit")
    print("3.Available spots")
    print("4.Stop")
    ch = input("Choice: ")

    if ch == "1":
        p.entry()
    elif ch == "2":
        p.exit()
    elif ch == "3":
        p.available()
    elif ch == "4":
        break

"""2. To-Do List Manager with Categories: Add tasks, set deadlines, assign priority, and filter by project or tag.
   
"""

class Todo:

    def __init__(self):
        self.tasks = []

    def add_task(self):
        name = input("Task name: ")
        category = input("Category: ")
        deadline = input("Deadline: ")
        priority = input("Priority (High/Medium/Low): ")
        project = input("Project/Tag: ")

        task = {
            "name": name,
            "category": category,
            "deadline": deadline,
            "priority": priority,
            "project": project
        }


        self.tasks.append(task)
        print("Task Added!")

    def show_tasks(self):
        print("\n--- Task List ---")
        for t in self.tasks:
            print("Task:", t["name"])
            print("Category:", t["category"])
            print("Deadline:", t["deadline"])
            print("Priority:", t["priority"])
            print("Project/Tag:", t["project"])
            print("------------------")


t = Todo()

while True:
    print("\n1.Add Task")
    print("2.Show Task")
    print("3.Exit")
    ch = input("Choice: ")

    if ch == "1":
        t.add_task()
    elif ch == "2":
        t.show_tasks()
    elif ch == "3":
        break

"""3.Billing System for Retail Store: Scan products, apply discounts, generate bills, and record transactions."""

class BillingSystem:

    def __init__(self):
        self.products = {}
        self.cart = {}
        self.total = 0

    def add_product(self):
        name = input("Enter product name: ")
        price = float(input("Enter product price: "))
        self.products[name] = price
        print("Product Added!")

    def scan_product(self):
        name = input("Enter product to scan: ")
        qty = int(input("Enter quantity: "))

        if name in self.products:
            self.cart[name] = self.cart.get(name, 0) + qty
            self.total += self.products[name] * qty
            print("Product Scanned!")
        else:
            print("Product not found!")

    def apply_discount(self):
        discount = float(input("Enter discount %: "))
        self.total -= (self.total * discount / 100)
        print("Discount Applied!")

    def generate_bill(self):
        print("\n------ BILL ------")
        for name, qty in self.cart.items():
            price = self.products[name]
            print(name, "x", qty, "=", price * qty)
        print("Total Amount:", self.total)
        print("------------------")

    def record_transaction(self):
        print("Transaction Recorded Successfully!")

store = BillingSystem()

while True:
    print("\n1.Add Product")
    print("2.Scan Product")
    print("3.Apply Discount")
    print("4.Generate Bill")
    print("5.Exit")
    choice = input("Enter choice: ")

    if choice == "1":
        store.add_product()
    elif choice == "2":
        store.scan_product()
    elif choice == "3":
        store.apply_discount()
    elif choice == "4":
        store.generate_bill()
        store.record_transaction()
    elif choice == "5":
        break
    else:
        print("Invalid Choice")

"""4.Movie Ticket Booking System: Check showtimes, book tickets, select seats, and print confirmation."""

class Show:
    def __init__(self, movie, time):
        self.movie = movie
        self.time = time


class Booking(Show):
    def __init__(self, movie, time):
        super().__init__(movie, time)
        self.available = ["A1", "A2", "A3","A4","A5","A6","A7","A8","A9","A10"]
        self.booked = []

    def menu(self):
        while True:
            print("\n1. Show Details")
            print("2. Available Seats")
            print("3. Book Seat")
            print("4. Booked Seats")
            print("5. Exit")

            choice = input("Enter choice: ")

            if choice == "1":
                print("Movie:", self.movie)
                print("Time:", self.time)

            elif choice == "2":
                print("Available Seats:", self.available)

            elif choice == "3":
                seat = input("Enter seat: ")
                if seat in self.available:
                    self.available.remove(seat)
                    self.booked.append(seat)
                    print("Seat Booked Successfully!")
                else:
                    print("Seat Not Available!")

            elif choice == "4":
                print("Booked Seats:", self.booked)

            elif choice == "5":
                print("Thank You!")
                break

            else:
                print("Invalid Choice!")


obj = Booking("Aamaram", "6 PM")
obj.menu()

"""5.College Result Management: Teachers enter marks, calculate GPA"""

class Student:
    def __init__(self, name, roll):
        self.name = name
        self.roll = roll

    def show_details(self):
        print("\nName:", self.name)
        print("Roll No:", self.roll)

class Result(Student):
    def __init__(self, name, roll, marks):
        super().__init__(name, roll)
        self.marks = marks   # list of marks

    def calculate_total(self):
        return sum(self.marks)

    def calculate_gpa(self):
        avg = sum(self.marks) / len(self.marks)
        gpa = avg / 10       # Simple GPA formula
        return round(gpa, 2)

    def display_result(self):
        self.show_details()
        print("Marks:", self.marks)
        print("Total:", self.calculate_total())
        print("GPA:", self.calculate_gpa())


name = input("Enter Student Name: ")
roll = input("Enter Roll No: ")

marks = []
for i in range(3):
    m = int(input("Enter marks of subject " + str(i+1) + ": "))
    marks.append(m)

obj = Result(name, roll, marks)
obj.display_result()

"""1.Password Manager: Securely store, add, edit, and retrieve user passwords using encryption."""

import hashlib
import json

class PasswordManager:

    def __init__(self):
        self.file = "passwords.json"

    def encrypt(self, password):
        return hashlib.sha256(password.encode()).hexdigest()

    def add_password(self, site, password):
        data = self.load()
        data[site] = self.encrypt(password)
        self.save(data)
        print("Password Added")

    def view_password(self, site):
        data = self.load()
        if site in data:
            print("Encrypted Password:", data[site])
        else:
            print("Site not found")

    def edit_password(self, site, new_password):
        data = self.load()
        if site in data:
            data[site] = self.encrypt(new_password)
            self.save(data)
            print("Password Updated")
        else:
            print("Site not found")

    def load(self):
        try:
            with open(self.file,"r") as f:
                return json.load(f)
        except:
            return {}

    def save(self,data):
        with open(self.file,"w") as f:
            json.dump(data,f)


username = "admin"
password = "1234"

u = input("Enter Username: ")
p = input("Enter Password: ")

if u == username and p == password:

    print("Login Successful")

    pm = PasswordManager()

while True:
    print("\n1 Add Password")
    print("2 View Password")
    print("3 Edit Password")
    print("4 Exit")

    ch = input("Enter choice: ")

    if ch == "1":
        site = input("Enter website: ")
        pwd = input("Enter password: ")
        pm.add_password(site,pwd)

    elif ch == "2":
        site = input("Enter website: ")
        pm.view_password(site)

    elif ch == "3":
        site = input("Enter website: ")
        pwd = input("Enter new password: ")
        pm.edit_password(site,pwd)

    elif ch == "4":
        break

"""2.Freelancer Marketplace Simulation: Register freelancers and clients, assign projects, and process payments."""

class Marketplace:

    def __init__(self):
        self.freelancers = []
        self.clients = []
        self.projects = []

    def register_freelancer(self, name):
        self.freelancers.append(name)
        print(name, "registered as Freelancer")

    def register_client(self, name):
        self.clients.append(name)
        print(name, "registered as Client")

    def assign_project(self, client, freelancer, project):
        self.projects.append((client, freelancer, project))
        print("Project", project, "assigned to", freelancer)

    def payment(self, freelancer, amount):
        print("Payment of", amount, "processed to", freelancer)


m = Marketplace()

while True:
    print("\n1 Register Freelancer")
    print("2 Register Client")
    print("3 Assign Project")
    print("4 Process Payment")
    print("5 Exit")

    ch = input("Enter choice: ")

    if ch == "1":
        name = input("Enter freelancer name: ")
        m.register_freelancer(name)

    elif ch == "2":
        name = input("Enter client name: ")
        m.register_client(name)

    elif ch == "3":
        client = input("Enter client name: ")
        freelancer = input("Enter freelancer name: ")
        project = input("Enter project name: ")
        m.assign_project(client, freelancer, project)

    elif ch == "4":
        freelancer = input("Enter freelancer name: ")
        amount = input("Enter payment amount: ")
        m.payment(freelancer, amount)

    elif ch == "5":
        break

"""3.Warehouse Automation System: Track goods movement, generate inventory reports, and forecast demand."""

class Inventory:
    def __init__(self):
        self.stock = {}

    def add_product(self):
        name = input("Enter product name: ")
        qty = int(input("Enter quantity: "))
        price = float(input("Enter price: "))

        if name in self.stock:
            self.stock[name][0] += qty
        else:
            self.stock[name] = [qty, price]

        print("Product Added Successfully!")

    def remove_product(self):
        name = input("Enter product name to remove: ")
        qty = int(input("Enter quantity to remove: "))

        if name in self.stock and self.stock[name][0] >= qty:
            self.stock[name][0] -= qty
            print("Product Removed Successfully!")
        else:
            print("Product Not Available or Not Enough Stock!")

    def show_report(self):
        print("\nInventory Report")
        total = 0

        for name in self.stock:
            qty, price = self.stock[name]
            value = qty * price
            total += value
            print(name, "Qty:", qty, "Value:", value)

        print("Total Stock Value:", total)


inventory = Inventory()

while True:
    print("\n1. Add Product")
    print("2. Remove Product")
    print("3. Show Report")
    print("4. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        inventory.add_product()
    elif choice == "2":
        inventory.remove_product()
    elif choice == "3":
        inventory.show_report()
    elif choice == "4":
        break
    else:
        print("Invalid Choice")

"""4.CRM (Customer Relationship Manager): Store customer info, manage communication logs, and track sales"""

class CRM:

    def __init__(self):
        self.customers = {}
        self.logs = {}
        self.sales = {}

    def add_customer(self, name, phone):
        self.customers[name] = phone
        print("Customer added")

    def add_log(self, name, message):
        if name not in self.logs:
            self.logs[name] = []
        self.logs[name].append(message)
        print("Communication log added")

    def add_sales(self, name, stage):
        self.sales[name] = stage
        print("Sales stage updated")

    def view_data(self):
        print("\nCustomers:", self.customers)
        print("Logs:", self.logs)
        print("Sales Pipeline:", self.sales)


crm = CRM()

while True:
    print("\n1 Add Customer")
    print("2 Add Communication Log")
    print("3 Update Sales Pipeline")
    print("4 View Data")
    print("5 Exit")

    ch = input("Enter choice: ")

    if ch == "1":
        name = input("Enter customer name: ")
        phone = input("Enter phone: ")
        crm.add_customer(name, phone)

    elif ch == "2":
        name = input("Enter customer name: ")
        msg = input("Enter communication message: ")
        crm.add_log(name, msg)

    elif ch == "3":
        name = input("Enter customer name: ")
        stage = input("Enter sales stage: ")
        crm.add_sales(name, stage)

    elif ch == "4":
        crm.view_data()

    elif ch == "5":
        break